CREATE OR ALTER VIEW vw_f_Vendas AS

SELECT
	nf.NUM_NOTA AS Nota,
	CAST(nf.DAT_EMISSAO AS DATE) AS [Data Emissao],
	nf.COD_CLIENTE AS [Codigo Cliente],
	c.CGC_CPF AS CNPJ,
	nf.COD_ESTABE AS [Codigo Estabelecimento],

	CASE
		WHEN nf.COD_ESTABE = 1 THEN 'MATRIZ'
		WHEN nf.COD_ESTABE = 2 THEN 'FILIAL'
		ELSE 'Sem estabelecimento vinculado'
	END AS Estabelecimento,

	ISNULL(nf.DES_LAYOUTPDE, 'SEM LAYOUT CADASTRADO') AS [Layout Pedido],

	CASE
		WHEN nf.DES_LAYOUTPDE = 'PORTALB2B' THEN 'PORTALB2B'
		ELSE 'Outros'
	END AS [Canal de Venda],

	CASE
		WHEN nf.DES_LAYOUTPDE = 'PORTALB2B' THEN 1
		ELSE 0
	END AS [Flag Venda PORTALB2B],

	CAST(nf.VLR_TOTALNOTA AS DECIMAL(18,2)) AS [Valor Venda],
	nf.COD_VENDEDOR AS [Codigo Vendedor]

FROM
	MOVNFS nf
INNER JOIN CADCLI c
	ON nf.COD_CLIENTE = c.COD_CLI
WHERE
	nf.DAT_EMISSAO IS NOT NULL
	AND nf.TIP_SAIDA = 'V'
	AND nf.DAT_CANCELAMENTO IS NULL
	AND nf.DAT_EMISSAO >= DATEADD(YEAR, -2,
        (SELECT MAX(DAT_EMISSAO) FROM MOVNFS))